[package]
name = "consolidated_map"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[features]
default = []

[dependencies]
storm = { git = "https://github.com/danylaporte/storm.git", default_features = false, optional = true }
